### ISSUE TITLE
求助关于数据集格式的问题

### ISSUE THREAD

**Issue by Franklin-L** [yongzhuo/ChatGLM3-SFT#2]
前辈请问现在的chatglm3的数据集格式发生变换了，就是变成了system、user和assistant，请问这个如果想实现多轮对话微调应该怎么构建数据集呀

**Comment by yongzhuo** [comment]
放history就好，[q,a,q,a]

格式为
<|system|>
xxx
<|user|>
xxx
<|assistant|>
xxx
<|user|>
xxx
<|assistant|>
xxx

代码中有实现
```python
    string_history = ""
    ids_history = []
    for idx, item in enumerate(history):
        content = item
        if idx % 2 == 0:
            id_role = ID_user
            token_role = TOKEN_USER
        else:
            id_role = ID_assistant
            token_role = TOKEN_ASSISTANT
        string_history += token_role + "\n" + content + "\n"
        id_history = [id_role] + tokenizer.encode("\n" + content + "\n",
                                                  is_split_into_words=True)[2:]
        ids_history.extend(id_history)

    ### 全量加入x, 同预训练(为了与多轮对话数据构造一致)
    ids_prompt_input = ids_prompt_system + ids_history + ids_text_input + ids_text_output
```

**Comment by Franklin-L** [comment]
> 放history就好，[q,a,q,a]
> 
> 格式为 <|system|> xxx <|user|> xxx <|assistant|> xxx <|user|> xxx <|assistant|> xxx
> 
> 代码中有实现
> 
> ```python
>     string_history = ""
>     ids_history = []
>     for idx, item in enumerate(history):
>         content = item
>         if idx % 2 == 0:
>             id_role = ID_user
>             token_role = TOKEN_USER
>         else:
>             id_role = ID_assistant
>             token_role = TOKEN_ASSISTANT
>         string_history += token_role + "\n" + content + "\n"
>         id_history = [id_role] + tokenizer.encode("\n" + content + "\n",
>                                                   is_split_into_words=True)[2:]
>         ids_history.extend(id_history)
> 
>     ### 全量加入x, 同预训练(为了与多轮对话数据构造一致)
>     ids_prompt_input = ids_prompt_system + ids_history + ids_text_input + ids_text_output
> ```

这个放history是什么意思呀我没太了解，是不是只要按照多轮对话新的格式构建数据集然后按照和单轮微调一样的步骤就可以了呀
